import sys

def help():
	print("usage: unique.(py|exe) [-n <number_of_UUIDs>] [-v <version_of_UUIDs>]")
	print("")
	print("generate a number of version-specific UUIDs")
	print("")
	print("supported switches/arguments.")
	print("  -c, --count\t specify the number of output UUIDs (1-65536)")
	print("  -v, --version\t specify which version the output UUIDs should be (0, 1, or 4)")
	print("      --help\t display this help message")
	print("")
	print("usage examples:")
	print("  generate 1 UUIDv4 (default behaviour)")
	print("\tunique")
	print("")
	print("  generate 25 UUIDv4")
	print("\tunique -c 25 -v 4")
	print("")
	print("  generate 100 UUIDv1")
	print("\tunique -c 100 -v 1")
	print("")
	print("")
	print("adam bonner, 2020, https://github.com/adambonneruk/uuid-generator/")
	print("python %s\n" % (sys.version,))
